FROM alpine:3.19

# Install .NET and test dependencies
RUN apk update && apk add --no-cache \
    bash \
    coreutils \
    curl \
    icu-data-full \
    icu-libs \
    iputils \
    krb5-libs \
    lldb \
    llvm \
    lttng-ust \
    musl-locales \
    openssl \
    python3 \
    sudo \
    tzdata
