FROM amd64/alpine:3.18

# Install .NET and test dependencies
RUN apk add --upgrade --no-cache \
        autoconf \
        automake \
        bash \
        build-base \
        clang \
        clang-dev \
        cmake \
        coreutils \
        curl \
        elfutils \
        file \
        gcc \
        gettext-dev \
        git \
        icu-data-full \
        icu-dev \
        jq \
        krb5-dev \
        libtool \
        libunwind-dev \
        linux-headers \
        lld \
        lldb-dev \
        llvm \
        lttng-ust-dev \
        make \
        numactl-dev \
        openssl \
        openssl-dev \
        paxctl \
        pigz \
        py3-lldb \
        py3-pip \
        python3-dev \
        shadow \
        sudo \
        tzdata \
        util-linux-dev \
        which \
        zlib-dev
