# Use this Dockerfile to create an image containing this repo and ImageBuilder
# Usage: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock imagebuilder <imagebuilder_args> .

FROM mcr.microsoft.com/dotnet-buildtools/image-builder:debian-20190305214722

WORKDIR /repo
COPY . .
