parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmdBuildJobTimeout: 60
  linuxArmBuildJobTimeout: 60
  customBuildInitSteps: []
  customCopyBaseImagesInitSteps: []
  linuxAmd64Pool: ''

stages:
- template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}

    ${{ if and(eq(variables['System.TeamProject'], parameters.publicProjectName), eq(parameters.linuxAmd64Pool, ''))}}:
      linuxAmd64Pool:
        name: NetCore-Public
        demands: ImageOverride -equals build.ubuntu.2204.amd64.open
    ${{ else }}:
      linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}

    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    linuxArmBuildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}

    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
