parameters:
  publishConfig: null
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmdBuildJobTimeout: 60
  linuxArmBuildJobTimeout: 60
  customBuildInitSteps: []
  customCopyBaseImagesInitSteps: []
  linuxAmd64Pool: ''
  versionsRepoRef: null
  additionalServiceConnections: []

stages:
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - template: /eng/docker-tools/templates/stages/setup-service-connections.yml@self
    parameters:
      serviceConnections:
      - name: ${{ parameters.publishConfig.internalMirrorAcr.serviceConnection.name }}
      - name: ${{ parameters.publishConfig.buildAcr.serviceConnection.name }}
      - name: ${{ parameters.publishConfig.publishAcr.serviceConnection.name }}
      - ${{ each serviceConnection in parameters.additionalServiceConnections }}:
        - name: ${{ serviceConnection.name }}

- template: /eng/docker-tools/templates/stages/dotnet/build-test-publish-repo.yml@self
  parameters:
    publishConfig: ${{ parameters.publishConfig }}
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}
    versionsRepoRef: ${{ parameters.versionsRepoRef }}

    ${{ if and(eq(variables['System.TeamProject'], parameters.publicProjectName), eq(parameters.linuxAmd64Pool, ''))}}:
      linuxAmd64Pool:
        name: NetCore-Public
        demands: ImageOverride -equals build.ubuntu.2204.amd64.open
    ${{ else }}:
      linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}

    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    linuxArmBuildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}

    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
