parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmdBuildJobTimeout: null
  linuxArmBuildJobTimeout: null
  customBuildInitSteps: []
  customCopyBaseImagesInitSteps: []
  linuxAmd64Pool:
    - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      name: NetCore1ESPool-Internal
      demands: ImageOverride -equals build.ubuntu.2204.amd64
    - ${{ else }}:
      name: NetCore-Public
      demands: ImageOverride -equals build.ubuntu.2204.amd64.open

stages:
- template: ../../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}

    linuxAmd64Pool: ${{ variables.linuxAmd64Pool }}
    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    linuxArmBuildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}

    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
