parameters:
  noCache: false
  internalProjectName: null
  publicProjectName: null
  linuxAmdBuildJobTimeout: 60
  linuxArmBuildJobTimeout: 60
  customBuildInitSteps: []
  customCopyBaseImagesInitSteps: []

stages:
- template: /eng/common/templates/stages/dotnet/build-test-publish-repo.yml@self
  parameters:
    noCache: ${{ parameters.noCache }}
    internalProjectName: ${{ parameters.internalProjectName }}
    publicProjectName: ${{ parameters.publicProjectName }}

    ${{ if eq(variables['System.TeamProject'], parameters.publicProjectName) }}:
      linuxAmd64Pool:
      name: NetCore-Public
      demands: ImageOverride -equals build.ubuntu.2204.amd64.open

    linuxAmdBuildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
    linuxArmBuildJobTimeout: ${{ parameters.linuxArmBuildJobTimeout }}

    customBuildInitSteps: ${{ parameters.customBuildInitSteps }}
    customCopyBaseImagesInitSteps: ${{ parameters.customCopyBaseImagesInitSteps }}
