parameters:
  matrix: {}

jobs:
- template: build-images.yml
  parameters:
    name: Build_Linux_amd64
    pool: # linuxAmd64Pool
      name: Hosted Ubuntu 1604
    architecture: amd64
    matrix: ${{ parameters.matrix }}
- template: build-images.yml
  parameters:
    name: Build_Linux_arm64v8
    pool: # linuxArm64v8Pool
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: DotNetCore-Docker-Public
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        name: DotNetCore-Docker
      demands:
      - agent.os -equals linux
      - RemoteDockerServerOS -equals linux
      - RemoteDockerServerArch -equals aarch64
    architecture: arm64
    matrix: ${{ parameters.matrix }}
    useRemoteDockerServer: true
- template: build-images.yml
  parameters:
    name: Build_Linux_arm32v7
    pool: # linuxArm32v7Pool
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: DotNetCore-Docker-Public
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        name: DotNetCore-Docker
      demands:
      - agent.os -equals linux
      - RemoteDockerServerOS -equals linux
      - RemoteDockerServerArch -equals aarch64
    architecture: arm
    matrix: ${{ parameters.matrix }}
    useRemoteDockerServer: true
