parameters:
  imageBuilderPath: null
  isPullRequestBuild: false

jobs:
- template: build-images.yml
  parameters:
    name: Build_Linux_amd64
    pool: # linuxAmd64Pool
      name: Hosted Ubuntu 1604
    architecture: amd64
    imageBuilderPath: ${{ parameters.imageBuilderPath }}
    isPullRequestBuild: ${{ parameters.isPullRequestBuild }}
- ${{ if eq(parameters.isPullRequestBuild, 'false') }}:
  - template: build-images.yml
    parameters:
      name: Build_Linux_arm64v8
      pool: # linuxArm64v8Pool
        name: DotNetCore-Docker
        demands:
        - agent.os -equals linux
        - RemoteDockerServerOS -equals linux
        - RemoteDockerServerArch -equals aarch64
      architecture: arm64
      imageBuilderPath: ${{ parameters.imageBuilderPath }}
      useRemoteDockerServer: true
      isPullRequestBuild: ${{ parameters.isPullRequestBuild }}
  - template: build-images.yml
    parameters:
      name: Build_Linux_arm32v7
      pool: # linuxArm32v7Pool
        name: DotNetCore-Docker
        demands:
        - agent.os -equals linux
        - RemoteDockerServerOS -equals linux
        - RemoteDockerServerArch -equals aarch64
      architecture: arm
      imageBuilderPath: ${{ parameters.imageBuilderPath }}
      useRemoteDockerServer: true
      isPullRequestBuild: ${{ parameters.isPullRequestBuild }}
