parameters:
  name: null
  pool: {}
  architecture: null
  useRemoteDockerServer: false
jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  timeoutInMinutes: 180
  variables:
    ${{ if eq(parameters.useRemoteDockerServer, 'true') }}:
      dockerArmRunArgs: 
        -v $(DOCKER_CERT_PATH):/docker-certs
        -e DOCKER_CERT_PATH=/docker-certs
        -e DOCKER_TLS_VERIFY=1
        -e DOCKER_HOST=tcp://$(DOCKER_HOST_IP):2376
    ${{ if eq(parameters.useRemoteDockerServer, 'false') }}:
      dockerArmRunArgs:
    imageBuilderTag: image-builder
    imageBuilderArgs:
      build
      --push
      --path $(imageBuilder.path)
      --manifest manifest.json
      --architecture ${{ parameters.architecture }}
      --username $(acr.userName)
      --password $(BotAccount-dotnet-docker-acr-bot-password)
      --registry-override $(acr.server)
      --repo-prefix $(publishRepoPrefix)
  steps:
  - template: ../steps/cleanup-docker-linux.yml
    parameters:
      runOnlyBasicCleanup: ${{ parameters.useRemoteDockerServer }}
  - script: docker build -t $(imageBuilderTag) --pull -f ./Dockerfile.linux.imagebuilder .
    displayName: Build Runner Image
  - script: >
      docker run
      --rm
      -v /var/run/docker.sock:/var/run/docker.sock
      -e DOCKER_REPO=$(acr.server)/$(publishRepoPrefix)dotnet-buildtools/prereqs
      $(dockerArmRunArgs)
      $(imageBuilderTag)
      $(imageBuilderArgs)
    displayName: Build Images
  - template: ../steps/cleanup-docker-linux.yml
    parameters:
      cleanupRemoteDockerServer: ${{ parameters.useRemoteDockerServer }}
