trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/ubuntu/18.04/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/ubuntu/18.04/*

variables:
- template: variables/common.yml

jobs:
  - template: jobs/build-image-legs.yml
    parameters:
      matrix: {
        "ubuntu18": {
          "imageBuilderPath": "src/ubuntu/18.04/*"
        }
      }
