trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/ubuntu/14.04/*
pr: none

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: src/ubuntu/14.04*

stages:
  - template: stages/build-repo.yml
