trigger: none
jobs:
- job:
  pool:
    name: DotNet-Build
    demands: agent.os -equals linux
  workspace:
    clean: all
  steps:
  - script: docker build -t runner --pull -f ./Dockerfile.linux.runner .
    displayName: Build Runner Image
  - script: >
      docker run
      --rm -v /var/run/docker.sock:/var/run/docker.sock
      runner
      pwsh -File ./build.ps1 -DockerfilePath $(imageBuilder.path) -ImageBuilderCustomArgs $(imageBuilder.buildArgs) -CleanupDocker
    displayName: Build Images
