trigger: none
pr: none

variables:
- group: DotNet-Docker-Common
- group: DotNet-Docker-Secrets

jobs:
- template: jobs/build-images.yml
  parameters:
    name: Build_Linux_amd64
    pool: # linuxAmd64Pool
      name: Hosted Ubuntu 1604
    architecture: amd64
- template: jobs/build-images.yml
  parameters:
    name: Build_Linux_arm64v8
    pool: # linuxArm64v8Pool
      name: DotNetCore-Docker
      demands:
      - agent.os -equals linux
      - RemoteDockerServerOS -equals linux
      - RemoteDockerServerArch -equals aarch64
    architecture: arm64
    useRemoteDockerServer: true
- template: jobs/build-images.yml
  parameters:
    name: Build_Linux_arm32v7
    pool: # linuxArm32v7Pool
      name: DotNetCore-Docker
      demands:
      - agent.os -equals linux
      - RemoteDockerServerOS -equals linux
      - RemoteDockerServerArch -equals aarch64
    architecture: arm
    useRemoteDockerServer: true
