trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/centos/6/*
pr: none

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: src/centos/6*

stages:
  - template: stages/build-repo.yml
