trigger: none
jobs:
- template: jobs/build-images.yml
  parameters:
    name: Build_Linux_amd64
    pool: # linuxAmd64Pool
      name: DotNet-Build
      demands:
      - agent.os -equals linux
    architecture: amd64
- template: jobs/build-images.yml
  parameters:
    name: Build_Linux_arm64v8
    pool: # linuxArm64v8Pool
      name: DotNetCore-Infra
      demands:
      - agent.os -equals linux
      - RemoteDockerServerOS -equals linux
      - RemoteDockerServerArch -equals arm64v8
    architecture: arm64
    useRemoteDockerServer: true
- template: jobs/build-images.yml
  parameters:
    name: Build_Linux_arm32v7
    pool: # linuxArm32v7Pool
      name: DotNetCore-Infra
      demands:
      - agent.os -equals linux
      - RemoteDockerServerOS -equals linux
      - RemoteDockerServerArch -equals arm32v7
    architecture: arm
    useRemoteDockerServer: true
