trigger: none
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - src/*
    - README.md

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path '*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      linuxAmdBuildJobTimeout: 210
      linuxAmdBuildPool: "NetCorePublic-Pool"
      linuxAmdBuildQueue: "BuildPool.Ubuntu.1604.Amd64.Open"
      customBuildInitSteps:
      - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
