trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/cbl-mariner/*
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self
- name: imageBuilder.pathArgs
  value: --path 'src/cbl-mariner/*'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    sdl:
      sourceRepositoriesToScan:
        include:
        - repository: InternalVersionsRepo
    stages:
    - template: /eng/pipelines/stages/build-test-publish-repo.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        linuxAmdBuildJobTimeout: 480
        customBuildInitSteps:
        - template: /eng/pipelines/steps/install-cross-build-prereqs.yml@self
