trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/ubuntu/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/ubuntu/*'

stages:
- template: stages/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmdBuildJobTimeout: 360
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      customCopyBaseImagesInitSteps:
      - template: ../../../pipelines/steps/set-base-image-override-options.yml
        parameters:
          variableName: customCopyBaseImagesArgs
          dockerfileOs: ubuntu
          baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
    customBuildInitSteps:
    - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
    - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      - template: ../../../pipelines/steps/set-base-image-override-options.yml
        parameters:
          variableName: imageBuilderBuildArgs
          dockerfileOs: ubuntu
          baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
  
