trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/ubuntu/20.04/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: git
    name: internal/dotnet-versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/ubuntu/20*'

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    customBuildInitSteps:
    - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
