trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - src/cbl-mariner/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/cbl-mariner/*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
