trigger: none
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - src/*
    - README.md

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path '*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      linuxAmdBuildJobTimeout: 210
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        linuxAmdBuildPool: "NetCorePublic-Pool"
        linuxAmdBuildQueue: "BuildPool.Ubuntu.1604.Amd64.Open"
      ${{ if eq(variables['System.TeamProject'], 'internal') }}:
        linuxAmdBuildPool: "NetCoreInternal-Pool"
        linuxAmdBuildQueue: "BuildPool.Ubuntu.1604.Amd64"
      customBuildInitSteps:
      - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
