trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/windowsservercore/20H2/*
pr: none

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/windowsservercore/20H2/*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
