trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/ubuntu/20*
pr: none

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/ubuntu/20*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      customBuildInitSteps:
      - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
