trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/centos/8/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/centos/8/*

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/centos/8*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      linuxAmdBuildJobTimeout: 210
