trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/debian/*
pr: none

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/debian/*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
