trigger: none
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - src/*
    - "*.md"
    - .git*
    - CODEOWNERS
    - LICENSE

resources:
  repositories:
  - repository: PublicVersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self
- name: imageBuilder.pathArgs
  value: --path '*'
# Since this pipeline is intended to test the infra, we don't want to trim the cached images from the matrix.
# This enables the entire pipeline to be exercised.
- name: trimCachedImagesForMatrix
  value: false

stages:
- template: /eng/pipelines/stages/build-test-publish-repo.yml@self
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmdBuildJobTimeout: 360
    linuxArmBuildJobTimeout: 300
    customBuildInitSteps:
    - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
