trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/*
pr: none

parameters:
- name: disableMatrixTrimming
  displayName: Disable matrix trimming
  type: boolean
  default: false

- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test or publish images that were built in a different pipeline run. When
    building new images, leave this value alone.
  type: string
  default: $(Build.BuildId)

schedules:
- cron: "0 5 1,15 * *"
  displayName: Monthly rebuild of all images
  branches:
    include:
    - main
  always: true

variables:
- template: /eng/pipelines/variables/common.yml@self
  parameters:
    disableMatrixTrimming: ${{ parameters.disableMatrixTrimming }}
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
- template: /eng/common/templates/variables/dotnet/secrets.yml@self
- name: publishEolAnnotations
  value: true
- name: Codeql.ExcludePathPatterns
  value: tests

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions
    ref: ${{ variables['gitHubVersionsRepoInfo.branch'] }}

extends:
  template: /eng/common/templates/1es.yml@self
  parameters:
    reposToExcludeFromScanning:
    - VersionsRepo
    stages:
    - template: /eng/common/templates/stages/dotnet/publish-config-prod.yml@self
      parameters:
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
        stagesTemplate: /eng/pipelines/stages/build-test-publish-repo.yml@self
        stagesTemplateParameters:
          versionsRepoRef: VersionsRepo
          linuxAmdBuildJobTimeout: 480
          linuxArmBuildJobTimeout: 300
          linuxAmd64Pool:
            name: NetCore1ESPool-Internal-XL
            image: 1es-ubuntu-2204
            os: linux
          ${{ if eq(variables['System.TeamProject'], 'internal') }}:
            customCopyBaseImagesInitSteps:
            - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
              parameters:
                variableName: customCopyBaseImagesArgs
                dockerfileOs: (centos|debian)
                baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
          customBuildInitSteps:
          - template: /eng/pipelines/steps/install-cross-build-prereqs.yml@self
          - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
            - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
              parameters:
                variableName: imageBuilderBuildArgs
                dockerfileOs: (centos|debian)
                baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
          # Force all images to be rebuilt when triggered by the schedule
          # See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1224
          ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
            noCache: true
          additionalServiceConnections:
          - name: $(marStatus.serviceConnectionName)
