trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/ubuntu/18.04/*
pr: none

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/ubuntu/18.04*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      linuxAmdBuildJobTimeout: 150
      linuxAmdBuildPool: "NetCoreInternal-Pool"
      linuxAmdBuildQueue: "BuildPool.Ubuntu.1604.Amd64"
      customBuildInitSteps:
      - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
