trigger: none
pr:
  branches:
    include:
    - master

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path '*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      linuxAmdBuildJobTimeout: 120
      customBuildInitSteps:
      - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
