trigger: none
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - src/*
    - README.md

resources:
  repositories:
  - repository: PublicVersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path '*'

stages:
- template: stages/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmdBuildJobTimeout: 360
    linuxArmBuildJobTimeout: 300
    customBuildInitSteps:
    - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
