trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/raspbian/*

pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/raspbian/*'

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
