trigger: none
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - template: /eng/pipelines/stages/build-test-publish-repo.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        linuxAmdBuildJobTimeout: 480
        linuxArmBuildJobTimeout: 300
        linuxAmd64Pool:
          name: NetCore1ESPool-Internal-XL
          image: 1es-ubuntu-2204
          os: linux
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          customCopyBaseImagesInitSteps:
          - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
            parameters:
              variableName: customCopyBaseImagesArgs
              dockerfileOs: (centos|debian)
              baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
        customBuildInitSteps:
        - template: /eng/pipelines/steps/install-cross-build-prereqs.yml@self
        - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
            parameters:
              variableName: imageBuilderBuildArgs
              dockerfileOs: (centos|debian)
              baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
