trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - eng/*
    - manifest.json
    - build.ps1
    - .dockerignore

resources:
  repositories:
  - repository: PublicVersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self
- name: imageBuilder.pathArgs
  value: --path '*'

stages:
- template: /eng/pipelines/stages/build-test-publish-repo.yml@self
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmdBuildJobTimeout: 360
    linuxArmBuildJobTimeout: 300
    customBuildInitSteps:
    - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
