trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/windowsservercore/ltsc2019/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/windowsservercore/ltsc2019/*

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/windowsservercore/ltsc2019/*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
