trigger: none
pr:
  branches:
    include:
    - main
    - master
  paths:
    include:
    - src/ubuntu/16.04/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/ubuntu/16.04*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
    parameters:
      linuxAmdBuildJobTimeout: 120
      customBuildInitSteps:
      - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
