trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/debian/*

pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: git
    name: internal/dotnet-versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/debian/*'

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
