trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/*
pr: none

parameters:
- name: disableMatrixTrimming
  displayName: Disable matrix trimming
  type: boolean
  default: false
- name: sourceBuildPipelineRunId
  displayName: >
    Source build pipeline run ID. This refers to runs of *this pipeline*.
    Override this parameter in combination with disabling the `Build` stage to
    test or publish images that were built in a different pipeline run.
    The default value should be left alone if you want to build new images.
  type: string
  default: $(Build.BuildId)

schedules:
- cron: "0 5 1,15 * *"
  displayName: Monthly rebuild of all images
  branches:
    include:
    - main
  always: true

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self
  parameters:
    disableMatrixTrimming: ${{ parameters.disableMatrixTrimming }}
    sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
- name: publishEolAnnotations
  value: true

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    serviceConnections:
    - name: $(internal-mirror.serviceConnectionName)
    - name: $(build.serviceConnectionName)
    - name: $(publish.serviceConnectionName)
    - name: $(marStatus.serviceConnectionName)
    stages:
    - template: /eng/pipelines/stages/build-test-publish-repo.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        linuxAmdBuildJobTimeout: 480
        linuxArmBuildJobTimeout: 300
        sourceBuildPipelineRunId: ${{ parameters.sourceBuildPipelineRunId }}
        linuxAmd64Pool:
          name: NetCore1ESPool-Internal-XL
          image: 1es-ubuntu-2204
          os: linux
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          customCopyBaseImagesInitSteps:
          - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
            parameters:
              variableName: customCopyBaseImagesArgs
              dockerfileOs: (centos|debian)
              baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
        customBuildInitSteps:
        - template: /eng/pipelines/steps/install-cross-build-prereqs.yml@self
        - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
            parameters:
              variableName: imageBuilderBuildArgs
              dockerfileOs: (centos|debian)
              baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
        # Force all images to be rebuilt when triggered by the schedule
        # See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1224
        ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
          noCache: true
