trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/centos/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/centos/*'

stages:
- template: stages/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmdBuildJobTimeout: 210
    linuxArmBuildJobTimeout: 300
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      customCopyBaseImagesInitSteps:
      - template: ../../../pipelines/steps/set-base-image-override-options.yml
        parameters:
          variableName: customCopyBaseImagesArgs
          dockerfileOs: centos
          baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
      customBuildInitSteps:
      - template: ../../../pipelines/steps/set-base-image-override-options.yml
        parameters:
          variableName: imageBuilderBuildArgs
          dockerfileOs: centos
          baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
