trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/centos/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: /eng/pipelines/variables/common.yml@self
- name: imageBuilder.pathArgs
  value: --path 'src/centos/*'

extends:
  template: /eng/common/templates/1es-official.yml@self
  parameters:
    stages:
    - template: /eng/pipelines/stages/build-test-publish-repo.yml@self
      parameters:
        internalProjectName: ${{ variables.internalProjectName }}
        publicProjectName: ${{ variables.publicProjectName }}
        linuxAmdBuildJobTimeout: 210
        linuxArmBuildJobTimeout: 300
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          customCopyBaseImagesInitSteps:
          - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
            parameters:
              variableName: customCopyBaseImagesArgs
              dockerfileOs: centos
              baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
          customBuildInitSteps:
          - template: /eng/pipelines/steps/set-base-image-override-options.yml@self
            parameters:
              variableName: imageBuilderBuildArgs
              dockerfileOs: centos
              baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
