trigger: none
pr:
  branches:
    include:
    - main
  paths:
    include:
    - src/ubuntu/*

resources:
  repositories:
  - repository: PublicVersionsRepo
    type: github
    endpoint: public
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/ubuntu/*'

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    linuxAmdBuildJobTimeout: 300
    customBuildInitSteps:
    - template: /eng/pipelines/steps/install-cross-build-prereqs.yml
