trigger: none
pr:
  branches:
    include:
    - master

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path '*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
