trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/fedora/*

resources:
  repositories:
  - repository: VersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/fedora/*'

stages:
  - template: ../common/templates/stages/build-test-publish-repo.yml
