name: CODEOWNERS Validation
run-name: ${{ github.actor }} is validating CODEOWNERS
on:
  pull_request:
    branches:
      - main

jobs:
  CheckDockerfileCodeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Ensure each CODEOWNER is a team
        if: always()
        run: ./validate-codeowners.sh ownersAreTeams

      - name: Check each Dockerfile for a CODEOWNER
        if: always()
        run: ./validate-codeowners.sh dockerfilesHaveOwners

      - name: Check for unused CODEOWNER paths
        if: always()
        run: ./validate-codeowners.sh pathsAreUsed
